src/Lyrixx/Bundle/FortuneBundle/Entity/Fortune.php
<?php

namespace Lyrixx\Bundle\FortuneBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Fortune
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="FortuneRepository")
 */
class Fortune
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string", length=255, nullable=true)
     */
    private $author;

    /**
     * @var string
     *
     * @ORM\Column(name="quotes", type="text")
     * @Assert\NotBlank()
     */
    private $quotes;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="votes", type="integer")
     */
    private $votes;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->votes = 0;
        $this->author = 'Anonymous';
    }

    public function vote($dir)
    {
        if ('up' == $dir) {
            $this->votes++;
        } elseif ('down' == $dir) {
            $this->votes--;
        } else {
            throw new \InvalidArgumentException(sprintf('The "%s" direction is not a valid choices ("down", "up").', $dir));
        }

        return $this;
    }

    public function getQuotesAsArray()
    {
        $quotes = array();

        foreach (explode("\n", $this->quotes) as $line) {
            if (preg_match('/^<(?P<nick>.*?)>\s*(?P<quote>.*)\s*$/', trim($line), $matches)) {
                $quotes[] = array(
                    'nick' => $matches['nick'],
                    'quote' => $matches['quote'],
                );
            } else {
                $quotes[] = array(
                    'nick' => '',
                    'quote' => trim($line),
                );
            }
        }

        return $quotes;
    }

    /**
     * @Assert\True(message="Quotes are not valid. It should respect the following format: '<nickname> quote...'")
     */
    public function isQuotesValid()
    {
        foreach (explode("\n", $this->quotes) as $line) {
            if (!preg_match('/^<.+>.+$/', trim($line), $matches)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set author
     *
     * @param  string  $author
     * @return Fortune
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set quotes
     *
     * @param  string  $quotes
     * @return Fortune
     */
    public function setQuotes($quotes)
    {
        $this->quotes = $quotes;

        return $this;
    }

    /**
     * Get quotes
     *
     * @return string
     */
    public function getQuotes()
    {
        return $this->quotes;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Get votes
     *
     * @return integer
     */
    public function getVotes()
    {
        return $this->votes;
    }
}

src/Lyrixx/Bundle/FortuneBundle/Controller/FrontController.php
<?php

namespace Lyrixx\Bundle\FortuneBundle\Controller;

use Lyrixx\Bundle\FortuneBundle\Entity\Fortune;
use Lyrixx\Bundle\FortuneBundle\Entity\Search;
use Lyrixx\Bundle\FortuneBundle\Form\FortuneType;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Exception\OutOfRangeCurrentPageException;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Template()
 * @Route("")
 * @Method("GET")
 */
class FrontController extends Controller
{
    /**
     * @Route("/", name="fortune_list", defaults={"orderBy"=null})
     * @Route("/top", name="fortune_list_top", defaults={"orderBy"="votes_desc"})
     * @Route("/flop", name="fortune_list_flop", defaults={"orderBy"="votes_asc"})
     */
    public function indexAction(Request $request)
    {
        $qb = $this->getDoctrine()
            ->getRepository('LyrixxFortuneBundle:Fortune')
            ->createQueryWithSearch(Search::createFromRequest($request))
        ;

        $pager = new Pagerfanta(new DoctrineORMAdapter($qb));
        try {
            $pager->setCurrentPage($request->query->getInt('page', 1));
        } catch (OutOfRangeCurrentPageException $e) {
            throw $this->createNotFoundException($e->getMessage());
        }

        return ['pager' => $pager];
    }

    /**
     * @Route("/new", name="fortune_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $fortune = new Fortune();
        $form = $this->createForm(FortuneType::class, $fortune);
        if ($form->handleRequest($request)->isValid() && $form->get('save')->isClicked()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($fortune);
            $em->flush();

            $request->getSession()->getFlashBag()->add('success', 'The fortune has been created');

            return $this->redirect($this->generateUrl('fortune_list'));
        }

        return array(
            'form' => $form->createView(),
            'preview' => $form->isValid(),
        );
    }

    /**
     * @Route("/{id}", name="fortune_show")
     */
    public function showAction(Fortune $fortune)
    {
    }

    /**
     * @Route("/vote/{id}/{dir}/{token}",
     *     name="fortune_vote",
     *     requirements={
     *         "id"="\d+",
     *         "dir"="up|down",
     *     }
     * )
     */
    public function voteAction(Request $request, Fortune $fortune, $dir, $token)
    {
        if (!$this->isCsrfTokenValid('', $token)) {
            throw $this->createNotFoundException('Invalid CSRF.');
        }

        $fortune->vote($dir);
        $this->getDoctrine()->getManager()->flush();

        if ($request->isXmlHttpRequest()) {
            return new JsonResponse(array('votes' => $fortune->getVotes()));
        }

        return $this->redirect($this->generateUrl('fortune_list'));
    }
}

src/Lyrixx/Bundle/FortuneBundle/Resources/views/Front/fortune.html.twig
<div class="panel panel-default">

    {{ include('@LyrixxFortune/Front/fortune_body.html.twig', {fortune: fortune}, with_context = false) }}


    <div class="panel-footer">
        <a href="{{ url('fortune_show', { id: fortune.id }) }}">
            #{{ fortune.id }}
        </a>
        by {{ fortune.author|default('Anonymous') }}
        at {{ fortune.createdAt|date('Y-m-d') }}
        <div class="pull-right votes" data-fortune-id="{{ fortune.id }}">
            <a href="{{ url('fortune_vote', { id: fortune.id, dir:'down', token: csrf_token('') }) }}"><span class="badge">-</span></a>
            <span class="label label-{{ 0 == fortune.votes ? 'warning' : (0 < fortune.votes ? 'success' : 'danger') }}">{{ fortune.votes }}</span>
            <a href="{{ url('fortune_vote', { id: fortune.id, dir:'up', token: csrf_token('') }) }}"><span class="badge">+</span></a>
        </div>
    </div>

</div>

src/Lyrixx/Bundle/FortuneBundle/Resources/views/Front/fortune.js.twig
<script>
    (function($) {
        $(function() {
            $('.votes').each(function(i, votes) {
                var $votes = $(votes);
                var fortuneId = $votes.data('fortune-id');
                if (fortune.storage.has(fortuneId)) {
                    $('a', $votes).css('visibility', 'hidden');
                }
            });

            $('.votes a').on('click', function(e) {
                e.preventDefault();

                var $this = $(this);

                var $parent = $this.parent();
                $('a', $parent).css('visibility', 'hidden');

                var fortuneId = $parent.data('fortune-id');
                if (fortune.storage.has(fortuneId)) {
                    alert('You have already voted for this fortunes');

                    return;
                };
                fortune.storage.add(fortuneId);

                $.ajax({
                    url: $this.attr('href'),
                    accepts: 'application/json',
                    statusCode: {
                        200: function(data) {
                            var $votesLabel = $('.label', $parent);

                            fortune.votes.updateClass($votesLabel, data.votes);
                            $votesLabel.html(data.votes);
                        },
                        400: function() {
                            alert('What did you try to do ???');
                        }
                    }
                })
            });
        });
    })(jQuery);
</script>

src/Lyrixx/Bundle/FortuneBundle/Resources/views/Front/fortune_body.html.twig
<dl class="dl-horizontal">
    {% for quote in fortune.quotesAsArray %}
        <dt>
            {% if quote.nick is defined %}
                <a href="{{ url('fortune_list', { q: quote.nick, exact: true }) }}">
                    {{ random_color(quote.nick) }}
                </a>
            {% endif %}
        </dt>
        <dd>{{ quote.quote }}</dd>
    {% endfor %}
</dl>

src/Lyrixx/Bundle/FortuneBundle/Resources/views/Front/index.html.twig
{% extends '@LyrixxFortune/layout.html.twig' %}

{% set query = app.request.query.all %}

{% block content %}
    {% if pager.currentPageResults|length %}
        {% if app.request.query.has('q') %}
            <p>

                Order results by
                <a href="{{ url('fortune_list', query|merge({q: app.request.query.get('q') }) ) }}">date</a>,
                <a href="{{ url('fortune_list_top', query|merge({q: app.request.query.get('q') }) ) }}">best vote</a>,
                <a href="{{ url('fortune_list_flop', query|merge({q: app.request.query.get('q') }) ) }}">worst vote</a>

            </p>
        {% endif %}

        {% for fortune in pager.currentPageResults %}
            {{ include('@LyrixxFortune/Front/fortune.html.twig', {fortune: fortune, token: csrf_token('')}, with_context = false) }}
        {% endfor %}

        {% if pager.haveToPaginate %}

            <ul class="pagination pagination-lg">
                <li{% if 1 == pager.currentPage %} class="disabled"{% endif %}>
                    <a href="{{ url(app.request.attributes.get('_route'), query|merge({page: 1}) ) }}">&laquo;&laquo;</a>
                </li>
                <li{% if not pager.hasPreviousPage %} class="disabled"{% endif %}>
                    <a href="{{ url(app.request.attributes.get('_route'), query|merge({page: pager.hasPreviousPage ?  pager.getPreviousPage : 1 }) ) }}">&laquo;</a>
                </li>
                {% for page in range(max(1, pager.currentPage - 5), min(pager.currentPage + 5, pager.nbPages)) %}
                    <li{% if page == pager.currentPage %} class="active"{% endif %}>
                        <a href="{{ url(app.request.attributes.get('_route'), query|merge({page: page}) ) }}">
                            {{ page }}{% if page == pager.currentPage %} <span class="sr-only">(current)</span>{% endif %}
                        </a>
                    </li>
                {% endfor %}
                <li{% if not pager.hasNextPage %} class="disabled"{% endif %}>
                    <a href="{{ url(app.request.attributes.get('_route'), query|merge({page:  pager.hasNextPage ? pager.getNextPage : pager.nbPages }) ) }}">&raquo;</a>
                </li>
                <li{% if not pager.hasNextPage %} class="disabled"{% endif %}>
                    <a href="{{ url(app.request.attributes.get('_route'), query|merge({page: pager.nbPages}) ) }}">&raquo;&raquo;</a>
                </li>
            </ul>
        {% endif %}

        <p class="pull-right">
            <a href="{{ url('fortune_new') }}" class="btn btn-primary">add a new one</a>
        </p>

    {% else %}
        {% if app.request.query.has('q') %}
            Nothing match your query,
        {% else %}
            There is no fortunes yet,
        {% endif %}
        but you can
        <a href="{{ url('fortune_new') }}" class="btn btn-primary">add a new one</a>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ include('@LyrixxFortune/Front/fortune.js.twig') }}
{% endblock %}

src/Lyrixx/Bundle/FortuneBundle/Resources/views/Front/new.html.twig
{% extends '@LyrixxFortune/layout.html.twig' %}

{% block content %}
    {% if preview %}
        <div class="panel panel-default">
            <div class="panel-heading">
                Preview:
            </div>
            {{ include('@LyrixxFortune/Front/fortune_body.html.twig', {fortune: form.vars.value}, with_context = false) }}
        </div>
    {% endif %}
    {{ form(form) }}
{% endblock %}

src/Lyrixx/Bundle/FortuneBundle/Resources/views/Front/show.html.twig
{% extends '@LyrixxFortune/layout.html.twig' %}

{% block content %}
    {{ include('@LyrixxFortune/Front/fortune.html.twig', {fortune: fortune, token: token}, with_context = false) }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ include('@LyrixxFortune/Front/fortune.js.twig') }}
{% endblock %}